version: '3.4'

services:
  sut:
    build: ./test
    volumes:
      - ./test:/tests-dir
    depends_on:
      - omnidb
      - lint
      - lint-tests
    links:
      - omnidb
    command: bash /tests-dir/run-test.sh

  lint:
    image: redcoolbeans/dockerlint
    volumes:
      - ./Dockerfile:/Dockerfile

  lint-tests:
    image: redcoolbeans/dockerlint
    volumes:
      - ./test/Dockerfile:/Dockerfile

  omnidb:
    build: .
